apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: argocd
  namespaceSelector:
    matchNames:
    - argocd
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
  - port: server
    interval: 30s
    path: /metrics
