apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: user-service-dev

build:
  artifacts:
  - image: user-service
    docker:
      dockerfile: src/Dockerfile
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  local:
    useBuildkit: true

deploy:
  helm:
    releases:
    - name: user-service
      chartPath: charts/user-service
      valuesFiles:
      - charts/user-service/values.yaml
      - charts/user-service/values-dev.yaml
      namespace: tke-gitops-dev
      createNamespace: true
      setValueTemplates:
        image.tag: "{{.IMAGE_TAG}}"

portForward:
- resourceType: Service
  resourceName: user-service
  namespace: tke-gitops-dev
  port: 8080
  localPort: 8080
