apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

namespace: demo-prod

patches:
- target:
    kind: Deployment
    name: demo-app
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 5
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 200m
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 256Mi

configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - SPRING_PROFILES_ACTIVE=prod
  - LOG_LEVEL=WARN
  - APP_VERSION=1.0.0
