version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-config
    ports:
      - "3316:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=optimization_db
    volumes:
      - mysql-config-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mysql-config-data:
