version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-lock
    ports:
      - "3314:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=optimization_db
    volumes:
      - mysql-lock-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mysql-lock-data:
