global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'go-exporter'
    static_configs:
      - targets: ['go-exporter:9300']
  - job_name: 'python-exporter'
    static_configs:
      - targets: ['python-exporter:9300']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']