version: '3.8'

services:
  loki:
    image: grafana/loki:2.9.2
    container_name: prom-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki-net

  promtail:
    image: grafana/promtail:2.9.2
    container_name: prom-promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
    depends_on:
      - loki
    networks:
      - loki-net

  grafana:
    image: grafana/grafana:10.2.0
    container_name: prom-grafana-loki
    ports:
      - "3091:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_data_loki:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - loki-net

networks:
  loki-net:
    driver: bridge

volumes:
  grafana_data_loki: